//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDHs = new HashSet<CTDH>();
        }
    
        public int MaDH { get; set; }
        public string DiaChi { get; set; }
        public string DienThoaiNhan { get; set; }
        public string TinhTrang { get; set; }
        public decimal TongTien { get; set; }
        public System.DateTime NgayDH { get; set; }
        public string TenNguoiNhan { get; set; }
        public string EmailNguoNhan { get; set; }
        public string MaKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
